name: Localize

on: 
  push:
    branches:
      - master
      - markavitale/localizationPipeline # TODO: Remove before check-in
  # Also run every day at midnight to pick up new localizations
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  Localize:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      name: Localize
      env:
        TDBUILD_TEAM_ID: ${{ secrets.TDBUILD_TEAM_ID }}
        TDBUILD_AAD_APPLICATION_CLIENT_ID: ${{ secrets.TDBUILD_AAD_APPLICATION_CLIENT_ID }}
        TDBUILD_AAD_APPLICATION_CLIENT_SECRET: ${{ secrets.TDBUILD_AAD_APPLICATION_CLIENT_SECRET }}
      run: scripts/localize.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.7.0
      with:
        commit-message: Latest localized resource files from Touchdown Build
        title: '[Localization] Localized Resource Files'
        body: 'Latest localized resource files from Touchdown Build'
        branch: tdbuild
        labels: Automated PR
        branch-suffix: timestamp
    
